version: '3.8'  # 指定兼容的 Compose 规范版本

services:        # 服务定义区块
  sui-redis:        # 服务名称（自定义）
    image: redis:7.4-alpine  # 镜像
    container_name: suiRedis  # 容器名称
    command: redis-server --bind 0.0.0.0 --port 6379 --appendonly yes --requirepass "suisuipingan" --user defaule on +@all >"suisuipingan"
    ports:
      - "8081:6379"
    networks:
      - suiNetwork   # 加入指定网络

  sui-mq:
    image: rabbitmq:3.9-management-alpine
    container_name: suiMQ
    environment:
      - RABBITMQ_DEFAULT_USER=sui      # 自定义账号
      - RABBITMQ_DEFAULT_PASS=suisuipingan   # 自定义密码
    ports:
      - "8082:5672"
      - "8083:15672"
    networks:
      - suiNetwork   # 加入指定网络

  # 1. 部署 Tracker 节点 (调度服务器)
  tracker:
    image: delron/fastdfs
    container_name: suiFastdfsTracker
    command: tracker
    volumes:
      - ./tracker_data:/var/fdfs
    network_mode: "host"

  # 2. 部署 Storage 节点 (存储服务器)
  storage:
    image: delron/fastdfs
    container_name: suiFastdfsStorage
    depends_on:
      - tracker
    command: storage
    environment:
      - TRACKER_SERVER=10.3.171.67:22122 
    volumes:
      - ./storage_data:/var/fdfs
    network_mode: "host"

  etcd:
    image: bitnami/etcd:3.5  # 建议指定具体主版本号
    ports:
      - "8084:2379"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:8084
    
  #es搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: es-node
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=suisuipingan
      - xpack.security.http.ssl.enabled=false
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - "8085:9200"
      - "8086:9300"
    networks:
      - suiNetwork

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=suisuipingan
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    ports:
      - "8087:5601"
    depends_on:
      - elasticsearch
    networks:
      - suiNetwork

# 定义网络
networks:  # 自定义网络（隔离通信）
  suiNetwork:
    driver: bridge  # 桥接模式