syntax = "proto3";
package suiApi;

import "base.proto";
import "file.proto";
import "user.proto";
import "video.proto";

option cc_generic_services = true;

message HttpBody {
  // 对应 HTTP Header 中的 Content-Type (例如 "video/mp2t", "image/jpeg", "text/html")
  string content_type = 1;
  // 对应 HTTP 正文，直接装载纯二进制数据
  bytes data = 2;
}

//请求路径: /httpServices/tempLogin
service httpServices {
  //用户服务
  rpc tempLogin(httpTempLoginReq) returns (HttpBody);
  rpc sessionLogin(httpSessionLoginReq) returns (HttpBody);
  rpc getEmailCode(httpGetEmailCodeReq) returns (HttpBody);
  rpc emailCodeLogin(httpEmailNumberLoginReq) returns (HttpBody);
  rpc passwordLogin(httpPasswordLoginReq) returns (HttpBody);
  rpc logout(httpLogoutReq) returns (HttpBody);
  rpc setUserAvatar(httpSetUserAvatarReq) returns (HttpBody);
  rpc setUserNickname(httpSetUserNicknameReq) returns (HttpBody);
  rpc setPassword(httpSetPasswordReq) returns (HttpBody);
  rpc setUserStatus(httpSetUserStatusReq) returns (HttpBody);
  rpc getUserInfo(httpUserInfoReq) returns (HttpBody);
  rpc newFollow(httpNewFollowReq) returns (HttpBody);
  rpc DelFollow(httpDelFollowReq) returns (HttpBody);
  rpc NewAdmin(httpNewAdminReq) returns (HttpBody);
  rpc DelAdmin(httpDelAdminReq) returns (HttpBody);
  rpc SetAdmin(httpSetAdminReq) returns (HttpBody);
  rpc GetAdmin(httpGetAdminReq) returns (HttpBody);
  rpc GetAdminList(httpGetAdminListReq) returns (HttpBody);
  rpc SetSalt(httpSetSaltReq) returns (HttpBody);
  rpc GetSalt(httpGetSaltReq) returns (HttpBody);

  //文件服务接口
  //图像上下传接口
  rpc uploadImage(httpUploadImageReq) returns (HttpBody);
  rpc downloadImage(httpDownloadImageReq) returns (HttpBody);

  rpc uploadFile(httpUploadFileReq) returns (HttpBody);
  rpc completeFileUpload(httpCompleteFileUploadReq) returns (HttpBody);

  //请求分片下载
  rpc getFileData(httpInitGetFileDataReq) returns (HttpBody);
  rpc downloadFile(httpDownloadFileReq) returns (HttpBody);

  //视频接口 //后续替换为http对外接口
  rpc newVideo(newVideoReq) returns (HttpBody);
  rpc deleteVideo(deleteVideoReq) returns (HttpBody);
  rpc isLikeVideo(isLikeVideoReq) returns (HttpBody);
  rpc setLikeVideo(setLikeVideoReq) returns (HttpBody);
  rpc playVideo(playVideoReq) returns (HttpBody);
  rpc addVideoSubtitle(addVideoSubtitleReq) returns (HttpBody);
  rpc getVideoSubtitle(getVideoSubtitleReq) returns (HttpBody);
  rpc reviewVideo(checkVideoReq) returns (HttpBody);
  rpc publishVideo(publishVideoReq) returns (HttpBody);
  rpc removeShelvesVideo(removeShelvesVideoReq) returns (HttpBody);
  rpc getUserVideoList(getUserVideoListReq) returns (HttpBody);
  rpc getStatusVideoList(getStatusVideoListReq) returns (HttpBody);
  rpc getHomeRandomVideoList(getHomeRandomVideoListReq) returns (HttpBody);
  rpc getCategoryVideoList(getCategoryVideoListReq) returns (HttpBody);
  rpc getTagVideoList(getTagVideoListReq) returns (HttpBody);
  rpc searchVideoList(searchVideoListReq) returns (HttpBody);
}
